#!/usr/bin/env python
# coding: utf-8

# In[44]:


#import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotnine as p9
import scipy.stats as stats
import missingno as msno


# In[45]:


#import medical data
medical = pd.read_csv("medical_clean.csv")
medical.info()


# In[46]:


#identify missing values in Vitamin D
medical['VitD_levels'].isnull()


# In[47]:


#identify missing values in Stroke
medical['Stroke'].isnull()


# In[48]:


t_result=stats.ttest_ind(medical[medical.Stroke=="Yes"].VitD_levels, medical[medical.Stroke=="No"].VitD_levels )
print(t_result)


# In[49]:


alpha=0.05
if (t_result[1] < alpha):
    print("Rejuct Null Hypothesis: Significant Difference")
else: 
    print("Fail to Reject Null Hypothesis: No Significant Difference")


# In[50]:


#univariate continuous variables
vitd_levels_mean=medical['VitD_levels'].mean()
vitd_levels_median=medical['VitD_levels'].median()
vitd_levels_std=medical['VitD_levels'].std()

AdditionCharge_mean=medical['Additional_charges'].mean()
AdditionCharge_median=medical['Additional_charges'].median()
AdditionCharge_std=medical['Additional_charges'].std()

print("Vitamin D levels Mean:", vitd_levels_mean)
print("Vitamin D levels Median:", vitd_levels_median)
print("Vitamin D levels Standard Deviation:", vitd_levels_std)

print("Add. Charge Mean:", AdditionCharge_mean)
print("Add. Charge Median:", AdditionCharge_median)
print("Add. Charge Standard Deviation:", AdditionCharge_std)

sns.histplot(x='VitD_levels', data=medical, kde=True)
plt.show()

sns.histplot(x='Additional_charges', data=medical)
plt.show()


# In[51]:


#univariate categorical variables
gender_counts = medical['Gender'].value_counts()
marital_counts = medical['Marital'].value_counts()
print("Gender Distribution:")
print(gender_counts)
print("Marital Status Distribution:")
print(marital_counts)
medical['Gender'].value_counts().plot.bar()
plt.show()
medical['Marital'].value_counts().plot.bar()
plt.show()


# In[52]:


#bivariate continuous variables
corr=medical['Age'].corr(medical['VitD_levels'])
plt.scatter(x='Age', y='VitD_levels', data=medical)
plt.title('Scatter Plot: Age vs Vitamin D Levels')
plt.show()


# In[53]:


#bivariate categorical variables
table=pd.crosstab(medical.Gender, medical.Stroke)
print(table)
table.plot.bar(stacked=False)
plt.show()


# In[ ]:



